"""
Generate workflow comparison metrics for roof PV outputs.

This utility compares workflow snapshots generated by ``workflow_comparison.py``:
- workflow0_normal_flat_roofs (WF0)
- workflow1_geometry_generator (WF1)

It can report:
- scenario totals (default)
- building-level diagnostics
- both
"""

from __future__ import annotations

import argparse
import csv
import glob
import math
import os
from typing import Any, Iterable


WORKFLOW_FOLDERS = {
    "WF0": "workflow0_normal_flat_roofs",
    "WF1": "workflow1_geometry_generator",
}
WORKFLOW_IDS = sorted(WORKFLOW_FOLDERS.keys())

DELTA_PAIRS = {
    "delta_total": ("WF1", "WF0"),
}

PV_METRICS = [
    "E_PV_gen_kWh",
    "area_PV_m2",
    "specific_yield_kWh_m2",
    "radiation_kWh",
    "radiation_kWh_m2",
]

ROOF_METRICS = [
    "roof_area_m2",
    "panel_area_installed_m2",
    "aw_tilt_deg",
    "aw_surface_tilt_deg",
    "aw_panel_tilt_deg_area",
    "aw_panel_tilt_deg_module",
    "aw_azimuth_deg",
    "aw_panel_azimuth_deg_area",
    "aw_panel_azimuth_deg_module",
    "orientation_share_flat",
    "orientation_share_N",
    "orientation_share_E",
    "orientation_share_S",
    "orientation_share_W",
    "panel_orientation_share_flat",
    "panel_orientation_share_N",
    "panel_orientation_share_E",
    "panel_orientation_share_S",
    "panel_orientation_share_W",
    "shading_cv_aw",
    "shading_p90_p10_Whm2",
]

ALL_METRICS = PV_METRICS + ROOF_METRICS


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create scenario/building metrics and WF deltas for roof-workflow-comparison outputs."
    )
    parser.add_argument(
        "--comparison-root",
        required=True,
        help="Path to outputs/data/roof-workflow-comparison.",
    )
    parser.add_argument(
        "--level",
        default="scenario",
        choices=["scenario", "building", "both"],
        help="Output level to generate.",
    )
    parser.add_argument(
        "--buildings",
        default="",
        help="Optional comma-separated building filter (e.g. B1000,B1001).",
    )
    parser.add_argument(
        "--pv-panels",
        default="PV1",
        help="Comma-separated PV panel ids, with or without PV_ prefix.",
    )
    parser.add_argument(
        "--out-dir",
        default="",
        help="Output folder. Default: --comparison-root.",
    )
    parser.add_argument(
        "--approx-panel-area-m2",
        default=1.8,
        type=float,
        help="Approximate module area for panel count estimation (count = area_installed_module_m2 / this value).",
    )
    return parser.parse_args()


def to_float(value: str | None) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def normalise_panel_ids(panel_arg: str) -> list[str]:
    panels: list[str] = []
    for token in panel_arg.split(","):
        raw = token.strip()
        if not raw:
            continue
        upper = raw.upper()
        if upper.startswith("PV_"):
            panel = upper
        elif upper.startswith("PV"):
            panel = f"PV_{upper}"
        else:
            panel = f"PV_{upper}"
        if panel not in panels:
            panels.append(panel)
    if not panels:
        raise ValueError("No valid panels parsed from --pv-panels.")
    return panels


def parse_building_filter(buildings_arg: str) -> set[str] | None:
    building_tokens = [token.strip() for token in buildings_arg.split(",") if token.strip()]
    if not building_tokens:
        return None
    return set(building_tokens)


def iter_csv_rows(path: str) -> Iterable[list[str]]:
    with open(path, newline="", encoding="utf-8") as fp:
        reader = csv.reader(fp)
        for row in reader:
            yield row


def read_building_totals(path: str) -> dict[str, dict[str, float]]:
    if not os.path.exists(path):
        return {}
    out: dict[str, dict[str, float]] = {}
    with open(path, newline="", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        for row in reader:
            building = (row.get("name") or "").strip()
            if not building:
                continue
            energy = to_float(row.get("E_PV_gen_kWh"))
            area = to_float(row.get("area_PV_m2"))
            radiation = to_float(row.get("radiation_kWh"))
            specific_yield = None if not area or area <= 0 else energy / area if energy is not None else None
            radiation_per_m2 = None if not area or area <= 0 else radiation / area if radiation is not None else None
            out[building] = {
                "E_PV_gen_kWh": energy,
                "area_PV_m2": area,
                "specific_yield_kWh_m2": specific_yield,
                "radiation_kWh": radiation,
                "radiation_kWh_m2": radiation_per_m2,
            }
    return out


def quadrant(azimuth_deg: float) -> str:
    az = azimuth_deg % 360.0
    if az < 45.0 or az >= 315.0:
        return "N"
    if az < 135.0:
        return "E"
    if az < 225.0:
        return "S"
    return "W"


def true_azimuth_from_normal(xdir: float, ydir: float) -> float:
    # xdir: east(+), west(-); ydir: north(+), south(-)
    # Result convention: 0=N, 90=E, 180=S, 270=W
    azimuth = math.degrees(math.atan2(xdir, ydir))
    if azimuth < 0:
        azimuth += 360.0
    return azimuth


def tilt_bin_label(panel_tilt_deg: float) -> str:
    if panel_tilt_deg < 5.0:
        return "0-5"
    if panel_tilt_deg < 15.0:
        return "5-15"
    if panel_tilt_deg < 30.0:
        return "15-30"
    return "30+"


def weighted_quantile(values: list[float], weights: list[float], q: float) -> float:
    if not values:
        return float("nan")
    if len(values) != len(weights):
        raise ValueError("Values and weights length mismatch.")
    if q <= 0:
        return min(values)
    if q >= 1:
        return max(values)
    pairs = sorted(zip(values, weights), key=lambda vw: vw[0])
    total_weight = sum(w for _, w in pairs)
    if total_weight <= 0:
        return float("nan")
    threshold = q * total_weight
    cumulative = 0.0
    for value, weight in pairs:
        cumulative += weight
        if cumulative >= threshold:
            return value
    return pairs[-1][0]


def compute_sensor_stats(sensor_rows: list[dict[str, Any]]) -> dict[str, float] | None:
    if not sensor_rows:
        return None

    roof_rows = [row for row in sensor_rows if row["TYPE"] == "roofs" and row["AREA_m2"] > 0]
    if not roof_rows:
        return None

    roof_area = sum(row["AREA_m2"] for row in roof_rows)
    if roof_area <= 0:
        return None

    module_area = sum(row["area_installed_module_m2"] for row in roof_rows if row["area_installed_module_m2"] > 0)

    aw_surface_tilt = sum(row["tilt_deg"] * row["AREA_m2"] for row in roof_rows) / roof_area
    aw_panel_tilt_area = sum(row["B_deg"] * row["AREA_m2"] for row in roof_rows) / roof_area
    aw_panel_azimuth_area = sum(row["surface_azimuth_deg"] * row["AREA_m2"] for row in roof_rows) / roof_area
    if module_area > 0:
        aw_panel_tilt_module = sum(row["B_deg"] * row["area_installed_module_m2"] for row in roof_rows) / module_area
        aw_panel_azimuth_module = (
            sum(row["surface_azimuth_deg"] * row["area_installed_module_m2"] for row in roof_rows) / module_area
        )
    else:
        aw_panel_tilt_module = None
        aw_panel_azimuth_module = None

    orient_areas = {"flat": 0.0, "N": 0.0, "E": 0.0, "S": 0.0, "W": 0.0}
    panel_orient_areas = {"flat": 0.0, "N": 0.0, "E": 0.0, "S": 0.0, "W": 0.0}
    radiation_values: list[float] = []
    radiation_weights: list[float] = []
    for row in roof_rows:
        area = row["AREA_m2"]
        module = max(0.0, row["area_installed_module_m2"])

        surface_tilt = row["tilt_deg"]
        if abs(surface_tilt) <= 1e-6:
            orient_areas["flat"] += area
        else:
            orient_areas[quadrant(row["surface_azimuth_deg"])] += area

        panel_tilt = row["B_deg"]
        if abs(panel_tilt) <= 1e-6:
            panel_orient_areas["flat"] += module
        else:
            panel_orient_areas[quadrant(row["surface_azimuth_deg"])] += module

        radiation_values.append(row["total_rad_Whm2"])
        radiation_weights.append(area)

    rad_mean = sum(v * w for v, w in zip(radiation_values, radiation_weights)) / roof_area
    rad_var = sum(((v - rad_mean) ** 2) * w for v, w in zip(radiation_values, radiation_weights)) / roof_area
    shading_cv = float("nan") if rad_mean <= 0 else math.sqrt(rad_var) / rad_mean
    p10 = weighted_quantile(radiation_values, radiation_weights, 0.10)
    p90 = weighted_quantile(radiation_values, radiation_weights, 0.90)

    return {
        "roof_area_m2": roof_area,
        "panel_area_installed_m2": module_area,
        # Backwards-compatible aliases
        "aw_tilt_deg": aw_surface_tilt,
        "aw_azimuth_deg": aw_panel_azimuth_area,
        # Explicit surface vs panel metrics
        "aw_surface_tilt_deg": aw_surface_tilt,
        "aw_panel_tilt_deg_area": aw_panel_tilt_area,
        "aw_panel_tilt_deg_module": aw_panel_tilt_module,
        "aw_panel_azimuth_deg_area": aw_panel_azimuth_area,
        "aw_panel_azimuth_deg_module": aw_panel_azimuth_module,
        "orientation_area_flat_m2": orient_areas["flat"],
        "orientation_area_N_m2": orient_areas["N"],
        "orientation_area_E_m2": orient_areas["E"],
        "orientation_area_S_m2": orient_areas["S"],
        "orientation_area_W_m2": orient_areas["W"],
        "orientation_share_flat": orient_areas["flat"] / roof_area,
        "orientation_share_N": orient_areas["N"] / roof_area,
        "orientation_share_E": orient_areas["E"] / roof_area,
        "orientation_share_S": orient_areas["S"] / roof_area,
        "orientation_share_W": orient_areas["W"] / roof_area,
        "panel_orientation_share_flat": None if module_area <= 0 else panel_orient_areas["flat"] / module_area,
        "panel_orientation_share_N": None if module_area <= 0 else panel_orient_areas["N"] / module_area,
        "panel_orientation_share_E": None if module_area <= 0 else panel_orient_areas["E"] / module_area,
        "panel_orientation_share_S": None if module_area <= 0 else panel_orient_areas["S"] / module_area,
        "panel_orientation_share_W": None if module_area <= 0 else panel_orient_areas["W"] / module_area,
        "shading_cv_aw": shading_cv,
        "shading_p90_p10_Whm2": p90 - p10,
    }


def load_sensor_stats(workflow_root: str) -> tuple[dict[str, dict[str, float]], dict[str, list[dict[str, Any]]]]:
    sensors_root = os.path.join(workflow_root, "potentials", "solar", "sensors")
    per_building: dict[str, dict[str, float]] = {}
    raw_rows: dict[str, list[dict[str, Any]]] = {}

    if not os.path.isdir(sensors_root):
        return per_building, raw_rows

    for path in glob.glob(os.path.join(sensors_root, "*_PV_sensors.csv")):
        filename = os.path.basename(path)
        building = filename.replace("_PV_sensors.csv", "")
        rows_iter = iter_csv_rows(path)
        try:
            header = next(rows_iter)
        except StopIteration:
            continue

        def idx(name: str) -> int:
            try:
                return header.index(name)
            except ValueError as exc:
                raise ValueError(f"Missing column '{name}' in {path}") from exc

        i_type = idx("TYPE")
        i_area = idx("AREA_m2")
        i_tilt = idx("tilt_deg")
        i_panel_tilt = idx("B_deg")
        i_az = idx("surface_azimuth_deg")
        i_rad = idx("total_rad_Whm2")
        i_module = idx("area_installed_module_m2")
        i_xdir = idx("Xdir")
        i_ydir = idx("Ydir")

        rows: list[dict[str, Any]] = []
        for row in rows_iter:
            if len(row) <= max(i_type, i_area, i_tilt, i_panel_tilt, i_az, i_rad, i_module, i_xdir, i_ydir):
                continue
            type_name = row[i_type].strip()
            area = to_float(row[i_area])
            tilt = to_float(row[i_tilt])
            panel_tilt = to_float(row[i_panel_tilt])
            azimuth = to_float(row[i_az])
            radiation = to_float(row[i_rad])
            module_area = to_float(row[i_module])
            xdir = to_float(row[i_xdir])
            ydir = to_float(row[i_ydir])
            if (
                area is None
                or tilt is None
                or panel_tilt is None
                or azimuth is None
                or radiation is None
                or xdir is None
                or ydir is None
            ):
                continue
            rows.append(
                {
                    "TYPE": type_name,
                    "AREA_m2": area,
                    "tilt_deg": tilt,
                    "B_deg": panel_tilt,
                    "surface_azimuth_deg": azimuth,
                    "total_rad_Whm2": radiation,
                    "area_installed_module_m2": 0.0 if module_area is None else module_area,
                    "Xdir": xdir,
                    "Ydir": ydir,
                }
            )
        raw_rows[building] = rows
        stats = compute_sensor_stats(rows)
        if stats is not None:
            per_building[building] = stats

    return per_building, raw_rows


def parse_numeric_row(
    key_fields: dict[str, Any],
    pv_metrics: dict[str, float] | None,
    sensor_metrics: dict[str, float] | None,
) -> dict[str, Any]:
    row = dict(key_fields)
    row["pv_data_available"] = pv_metrics is not None
    row["sensor_data_available"] = sensor_metrics is not None
    if not pv_metrics and not sensor_metrics:
        row["missing_status"] = "missing_pv_and_sensors"
    elif not pv_metrics:
        row["missing_status"] = "missing_pv"
    elif not sensor_metrics:
        row["missing_status"] = "missing_sensors"
    else:
        row["missing_status"] = "ok"

    for metric in PV_METRICS:
        row[metric] = None if pv_metrics is None else pv_metrics.get(metric)
    for metric in ROOF_METRICS:
        row[metric] = None if sensor_metrics is None else sensor_metrics.get(metric)
    return row


def aggregate_scenario_rows(building_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in building_rows:
        key = (row["workflow_id"], row["pv_panel"])
        grouped.setdefault(key, []).append(row)

    scenario_rows: list[dict[str, Any]] = []
    for (workflow_id, pv_panel), rows in sorted(grouped.items()):
        workflow_name = rows[0]["workflow_name"]

        pv_valid = [r for r in rows if r["pv_data_available"]]
        sensor_valid = [r for r in rows if r["sensor_data_available"]]

        e_sum = sum(r["E_PV_gen_kWh"] for r in pv_valid if r["E_PV_gen_kWh"] is not None)
        area_sum = sum(r["area_PV_m2"] for r in pv_valid if r["area_PV_m2"] is not None)
        rad_sum = sum(r["radiation_kWh"] for r in pv_valid if r["radiation_kWh"] is not None)
        specific_yield = None if area_sum <= 0 else e_sum / area_sum
        radiation_per_m2 = None if area_sum <= 0 else rad_sum / area_sum

        roof_area_sum = sum(r["roof_area_m2"] for r in sensor_valid if r["roof_area_m2"] is not None)
        panel_area_installed_sum = sum(
            r["panel_area_installed_m2"] for r in sensor_valid if r["panel_area_installed_m2"] is not None
        )
        if roof_area_sum > 0:
            aw_surface_tilt = (
                sum(
                    r["aw_surface_tilt_deg"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["aw_surface_tilt_deg"] is not None
                )
                / roof_area_sum
            )
            aw_panel_tilt_area = (
                sum(
                    r["aw_panel_tilt_deg_area"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["aw_panel_tilt_deg_area"] is not None
                )
                / roof_area_sum
            )
            aw_panel_az_area = (
                sum(
                    r["aw_panel_azimuth_deg_area"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["aw_panel_azimuth_deg_area"] is not None
                )
                / roof_area_sum
            )
            share_flat = (
                sum(
                    r["orientation_share_flat"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_flat"] is not None
                )
                / roof_area_sum
            )
            share_n = (
                sum(
                    r["orientation_share_N"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_N"] is not None
                )
                / roof_area_sum
            )
            share_e = (
                sum(
                    r["orientation_share_E"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_E"] is not None
                )
                / roof_area_sum
            )
            share_s = (
                sum(
                    r["orientation_share_S"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_S"] is not None
                )
                / roof_area_sum
            )
            share_w = (
                sum(
                    r["orientation_share_W"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_W"] is not None
                )
                / roof_area_sum
            )

            shading_cv = (
                sum(r["shading_cv_aw"] * r["roof_area_m2"] for r in sensor_valid if r["shading_cv_aw"] is not None)
                / roof_area_sum
            )
            shading_spread = (
                sum(
                    r["shading_p90_p10_Whm2"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["shading_p90_p10_Whm2"] is not None
                )
                / roof_area_sum
            )
        else:
            aw_surface_tilt = None
            aw_panel_tilt_area = None
            aw_panel_az_area = None
            share_flat = None
            share_n = None
            share_e = None
            share_s = None
            share_w = None
            shading_cv = None
            shading_spread = None

        if panel_area_installed_sum > 0:
            aw_panel_tilt_module = (
                sum(
                    r["aw_panel_tilt_deg_module"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["aw_panel_tilt_deg_module"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            aw_panel_az_module = (
                sum(
                    r["aw_panel_azimuth_deg_module"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["aw_panel_azimuth_deg_module"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_flat = (
                sum(
                    r["panel_orientation_share_flat"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_flat"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_n = (
                sum(
                    r["panel_orientation_share_N"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_N"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_e = (
                sum(
                    r["panel_orientation_share_E"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_E"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_s = (
                sum(
                    r["panel_orientation_share_S"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_S"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_w = (
                sum(
                    r["panel_orientation_share_W"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_W"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
        else:
            aw_panel_tilt_module = None
            aw_panel_az_module = None
            panel_share_flat = None
            panel_share_n = None
            panel_share_e = None
            panel_share_s = None
            panel_share_w = None

        row = {
            "workflow_id": workflow_id,
            "workflow_name": workflow_name,
            "pv_panel": pv_panel,
            "building": "__SCENARIO__",
            "pv_data_available": bool(pv_valid),
            "sensor_data_available": bool(sensor_valid),
            "missing_status": "ok" if pv_valid and sensor_valid else "incomplete",
            "E_PV_gen_kWh": e_sum if pv_valid else None,
            "area_PV_m2": area_sum if pv_valid else None,
            "specific_yield_kWh_m2": specific_yield,
            "radiation_kWh": rad_sum if pv_valid else None,
            "radiation_kWh_m2": radiation_per_m2,
            "roof_area_m2": roof_area_sum if sensor_valid else None,
            "panel_area_installed_m2": panel_area_installed_sum if sensor_valid else None,
            "aw_tilt_deg": aw_surface_tilt,
            "aw_surface_tilt_deg": aw_surface_tilt,
            "aw_panel_tilt_deg_area": aw_panel_tilt_area,
            "aw_panel_tilt_deg_module": aw_panel_tilt_module,
            "aw_azimuth_deg": aw_panel_az_area,
            "aw_panel_azimuth_deg_area": aw_panel_az_area,
            "aw_panel_azimuth_deg_module": aw_panel_az_module,
            "orientation_share_flat": share_flat,
            "orientation_share_N": share_n,
            "orientation_share_E": share_e,
            "orientation_share_S": share_s,
            "orientation_share_W": share_w,
            "panel_orientation_share_flat": panel_share_flat,
            "panel_orientation_share_N": panel_share_n,
            "panel_orientation_share_E": panel_share_e,
            "panel_orientation_share_S": panel_share_s,
            "panel_orientation_share_W": panel_share_w,
            "shading_cv_aw": shading_cv,
            "shading_p90_p10_Whm2": shading_spread,
            "n_buildings_with_pv_data": len(pv_valid),
            "n_buildings_with_sensor_data": len(sensor_valid),
        }
        scenario_rows.append(row)

    return scenario_rows


def build_panel_placement_rows(
    workflow_data: dict[str, dict[str, Any]],
    panels: list[str],
    buildings: list[str],
    approx_panel_area_m2: float,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for workflow_id, wf_data in workflow_data.items():
        workflow_name = wf_data["workflow_name"]
        sensor_raw_rows_by_building: dict[str, list[dict[str, Any]]] = wf_data["sensor_raw_rows"]

        for building in buildings:
            roof_rows = [
                row
                for row in sensor_raw_rows_by_building.get(building, [])
                if row.get("TYPE") == "roofs" and row.get("area_installed_module_m2", 0.0) > 0
            ]
            if not roof_rows:
                for panel in panels:
                    rows.append(
                        {
                            "workflow_id": workflow_id,
                            "workflow_name": workflow_name,
                            "pv_panel": panel,
                            "building": building,
                            "direction": "",
                            "tilt_bin_deg": "",
                            "panel_area_m2": None,
                            "panel_count_approx": None,
                            "share_of_panel_area": None,
                            "missing_status": "missing_sensor_rows",
                        }
                    )
                continue

            base_panel_area = sum(row["area_installed_module_m2"] for row in roof_rows)
            bins: dict[tuple[str, str], dict[str, float]] = {}
            for sensor in roof_rows:
                panel_tilt = sensor["B_deg"]
                true_azimuth = true_azimuth_from_normal(sensor["Xdir"], sensor["Ydir"])
                direction = quadrant(true_azimuth)
                bin_key = (direction, tilt_bin_label(panel_tilt))
                if bin_key not in bins:
                    bins[bin_key] = {"panel_area_m2": 0.0, "radiation_weight_Wh": 0.0}
                module_area = sensor["area_installed_module_m2"]
                bins[bin_key]["panel_area_m2"] += module_area
                # Proxy for directional energy split: annual irradiation per sensor * installed module area
                bins[bin_key]["radiation_weight_Wh"] += sensor["total_rad_Whm2"] * module_area

            for panel in panels:
                panel_totals = wf_data["panel_totals"][panel]
                panel_metrics = panel_totals.get(building)
                if panel_metrics is None or panel_metrics.get("area_PV_m2") is None:
                    rows.append(
                        {
                            "workflow_id": workflow_id,
                            "workflow_name": workflow_name,
                            "pv_panel": panel,
                            "building": building,
                            "direction": "",
                            "tilt_bin_deg": "",
                            "panel_area_m2": None,
                            "panel_count_approx": None,
                            "share_of_panel_area": None,
                            "radiation_kWh_approx": None,
                            "share_of_radiation": None,
                            "E_PV_gen_kWh_approx": None,
                            "share_of_generation": None,
                            "missing_status": "missing_panel_totals",
                        }
                    )
                    continue

                target_panel_area = panel_metrics["area_PV_m2"]
                scale = 0.0 if base_panel_area <= 0 else target_panel_area / base_panel_area
                total_weight = sum(bin_data["radiation_weight_Wh"] for bin_data in bins.values())
                total_radiation = panel_metrics.get("radiation_kWh")
                total_generation = panel_metrics.get("E_PV_gen_kWh")

                for (direction, tilt_bin), bin_data in sorted(bins.items()):
                    panel_area = bin_data["panel_area_m2"] * scale
                    panel_count = None if approx_panel_area_m2 <= 0 else panel_area / approx_panel_area_m2
                    share = None if target_panel_area <= 0 else panel_area / target_panel_area
                    weight_share = None if total_weight <= 0 else bin_data["radiation_weight_Wh"] / total_weight
                    radiation_kwh_approx = None if total_radiation is None or weight_share is None else total_radiation * weight_share
                    generation_kwh_approx = None if total_generation is None or weight_share is None else total_generation * weight_share
                    rows.append(
                        {
                            "workflow_id": workflow_id,
                            "workflow_name": workflow_name,
                            "pv_panel": panel,
                            "building": building,
                            "direction": direction,
                            "tilt_bin_deg": tilt_bin,
                            "panel_area_m2": panel_area,
                            "panel_count_approx": panel_count,
                            "share_of_panel_area": share,
                            "radiation_kWh_approx": radiation_kwh_approx,
                            "share_of_radiation": weight_share,
                            "E_PV_gen_kWh_approx": generation_kwh_approx,
                            "share_of_generation": weight_share,
                            "missing_status": "ok",
                        }
                    )
    return rows


def build_delta_rows(base_rows: list[dict[str, Any]], key_fields: list[str]) -> list[dict[str, Any]]:
    grouped: dict[tuple[Any, ...], dict[str, dict[str, Any]]] = {}
    for row in base_rows:
        key = tuple(row[field] for field in key_fields)
        grouped.setdefault(key, {})[row["workflow_id"]] = row

    out: list[dict[str, Any]] = []
    for key, wf_rows in sorted(grouped.items()):
        row: dict[str, Any] = {field: value for field, value in zip(key_fields, key)}
        for workflow_id in WORKFLOW_IDS:
            row[f"{workflow_id.lower()}_present"] = workflow_id in wf_rows
        if all(workflow_id in wf_rows for workflow_id in WORKFLOW_IDS):
            row["missing_status"] = "ok"
        else:
            missing = [workflow_id for workflow_id in WORKFLOW_IDS if workflow_id not in wf_rows]
            row["missing_status"] = f"missing_{'_'.join(w.lower() for w in missing)}"

        for metric in ALL_METRICS:
            values = {
                workflow_id: (wf_rows[workflow_id].get(metric) if workflow_id in wf_rows else None)
                for workflow_id in WORKFLOW_IDS
            }
            row[f"value_wf0_{metric}"] = values["WF0"]
            row[f"value_wf1_{metric}"] = values["WF1"]

            for delta_name, (lhs, rhs) in DELTA_PAIRS.items():
                lhs_val = values.get(lhs)
                rhs_val = values.get(rhs)
                row[f"{delta_name}_{metric}"] = None if lhs_val is None or rhs_val is None else lhs_val - rhs_val
        out.append(row)
    return out


def round_for_output(value: Any) -> Any:
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return ""
        return round(value, 6)
    if value is None:
        return ""
    return value


def write_csv(path: str, rows: list[dict[str, Any]], field_order: list[str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=field_order, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: round_for_output(row.get(field)) for field in field_order})


def build_field_order(rows: list[dict[str, Any]], preferred_first: list[str]) -> list[str]:
    keys = set()
    for row in rows:
        keys.update(row.keys())
    remaining = sorted(k for k in keys if k not in preferred_first)
    return [k for k in preferred_first if k in keys] + remaining


def main() -> None:
    args = parse_args()
    comparison_root = os.path.abspath(args.comparison_root)
    if not os.path.isdir(comparison_root):
        raise NotADirectoryError(f"Comparison root does not exist: {comparison_root}")

    out_dir = os.path.abspath(args.out_dir) if args.out_dir else comparison_root
    panels = normalise_panel_ids(args.pv_panels)
    building_filter = parse_building_filter(args.buildings)

    workflow_data: dict[str, dict[str, Any]] = {}
    for workflow_id, folder_name in WORKFLOW_FOLDERS.items():
        workflow_root = os.path.join(comparison_root, folder_name)
        sensor_stats, raw_sensor_rows = load_sensor_stats(workflow_root)

        panel_totals: dict[str, dict[str, dict[str, float]]] = {}
        for panel in panels:
            filename = f"{panel}_total_buildings.csv"
            totals_path = os.path.join(workflow_root, "potentials", "solar", filename)
            panel_totals[panel] = read_building_totals(totals_path)

        workflow_data[workflow_id] = {
            "workflow_name": folder_name,
            "sensor_stats": sensor_stats,
            "sensor_raw_rows": raw_sensor_rows,
            "panel_totals": panel_totals,
        }

    all_buildings: set[str] = set()
    for wf_data in workflow_data.values():
        all_buildings.update(wf_data["sensor_stats"].keys())
        for panel in panels:
            all_buildings.update(wf_data["panel_totals"][panel].keys())
    if building_filter is not None:
        all_buildings = {b for b in all_buildings if b in building_filter}

    building_rows: list[dict[str, Any]] = []
    for workflow_id, wf_data in workflow_data.items():
        workflow_name = wf_data["workflow_name"]
        sensor_stats = wf_data["sensor_stats"]
        for panel in panels:
            pv_totals = wf_data["panel_totals"][panel]
            for building in sorted(all_buildings):
                pv_metrics = pv_totals.get(building)
                roof_metrics = sensor_stats.get(building)
                key_fields = {
                    "workflow_id": workflow_id,
                    "workflow_name": workflow_name,
                    "pv_panel": panel,
                    "building": building,
                }
                building_rows.append(parse_numeric_row(key_fields, pv_metrics, roof_metrics))

    scenario_rows = aggregate_scenario_rows(building_rows)
    scenario_delta_rows = build_delta_rows(scenario_rows, key_fields=["pv_panel"])
    building_delta_rows = build_delta_rows(building_rows, key_fields=["pv_panel", "building"])
    panel_placement_rows = build_panel_placement_rows(
        workflow_data=workflow_data,
        panels=panels,
        buildings=sorted(all_buildings),
        approx_panel_area_m2=args.approx_panel_area_m2,
    )

    outputs_written: list[str] = []
    if args.level in ("scenario", "both"):
        scenario_metrics_fields = build_field_order(
            scenario_rows,
            preferred_first=[
                "workflow_id",
                "workflow_name",
                "pv_panel",
                "pv_data_available",
                "sensor_data_available",
                "missing_status",
                "n_buildings_with_pv_data",
                "n_buildings_with_sensor_data",
            ],
        )
        scenario_delta_fields = build_field_order(
            scenario_delta_rows,
            preferred_first=["pv_panel", "wf0_present", "wf1_present", "missing_status"],
        )
        path_metrics = os.path.join(out_dir, "scenario_metrics.csv")
        path_deltas = os.path.join(out_dir, "scenario_deltas.csv")
        write_csv(path_metrics, scenario_rows, scenario_metrics_fields)
        write_csv(path_deltas, scenario_delta_rows, scenario_delta_fields)
        outputs_written.extend([path_metrics, path_deltas])

    if args.level in ("building", "both"):
        building_metrics_fields = build_field_order(
            building_rows,
            preferred_first=[
                "workflow_id",
                "workflow_name",
                "pv_panel",
                "building",
                "pv_data_available",
                "sensor_data_available",
                "missing_status",
            ],
        )
        building_delta_fields = build_field_order(
            building_delta_rows,
            preferred_first=["pv_panel", "building", "wf0_present", "wf1_present", "missing_status"],
        )
        path_metrics = os.path.join(out_dir, "building_metrics.csv")
        path_deltas = os.path.join(out_dir, "building_deltas.csv")
        write_csv(path_metrics, building_rows, building_metrics_fields)
        write_csv(path_deltas, building_delta_rows, building_delta_fields)
        outputs_written.extend([path_metrics, path_deltas])

    if args.level in ("building", "both"):
        panel_placement_fields = [
            "workflow_id",
            "workflow_name",
            "pv_panel",
            "building",
            "direction",
            "tilt_bin_deg",
            "panel_area_m2",
            "panel_count_approx",
            "share_of_panel_area",
            "radiation_kWh_approx",
            "share_of_radiation",
            "E_PV_gen_kWh_approx",
            "share_of_generation",
            "missing_status",
        ]
        path_panel_placement = os.path.join(out_dir, "panel_placement_summary.csv")
        write_csv(path_panel_placement, panel_placement_rows, panel_placement_fields)
        outputs_written.append(path_panel_placement)

    print("Workflow metrics report completed.")
    print(f"comparison_root: {comparison_root}")
    print(f"level: {args.level}")
    print(f"pv_panels: {', '.join(panels)}")
    if building_filter is not None:
        print(f"building_filter: {', '.join(sorted(building_filter))}")
    print("Wrote:")
    for path in outputs_written:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
